[theme]
primaryColor = "#D4AF37"         # Gold (Buton ka rang)
backgroundColor = "#0F2027"      # Deep Blue/Black (Raat ka rang)
secondaryBackgroundColor = "#203A43" # Sidebar ka rang (Thoda halka)
textColor = "#FFFFFF"            # White (Likha hua saaf dikhega)
font = "sans serif"

